# ---

# - name: "Add node.js for source"
#   become: true
#   shell: |
#     curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
# - name: "Install Node.js 13"
#   become: true
#   apt:
#     name: ["node.js"]
#     state: latest
#     update_cache: yes
# - name: "Install PM2 Globally"
#   npm:
#     name: pm2
#     global: yes
# - name: "move env variables to /etc/profile.d/"
#   become: true
#   copy:
#     src: myenv.sh
#     dest: /etc/profile.d/
# ---


# - name: "update apt packages."
#   become: yes
#   apt:
#     update_cache: yes

# - name: "upgrade packages"
#   become: yes
#   apt:
#     upgrade: yes

# - name: "remove dependencies that are no longer required"
#   become: yes
#   apt:
#     autoremove: yes

# - name: "install nodejs and npm"
#   become: yes
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "install n"
#   become: yes
#   npm:
#     name: n
#     global: yes
#     production: yes

# - name: "install nodejs 13.8.0"
#   become: yes
#   shell: n 13.8.0
  
# - name: "install pm2"
#   become: yes
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present

# - name: "move env variables to /etc/profile.d/"
#   become: true
#   copy:
#     src: myenv.sh
#     dest: /etc/profile.d/

---

- name: "update apt"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present