---
- name: upgrade packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: "Add Node.js 13"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

- name: "Install Node.js 13"
  become: true
  apt:
    name: ["node.js"]
    state: latest
    update_cache: yes

    
- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
    state:  latest
    production: yes

- name: "move env variables to /etc/profile.d/"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d/


